### ISSUE TITLE
Setup.py does not include project requirements

### ISSUE THREAD

**Issue by peterHoburg** [leogomezz4t/PyTextNow_API#10]
setup.py should have a section called  `install_requires` that includes all the dependencies of the project. In this case 

```
    install_requires=["requests >  2"]
```
requests > 2 in this case is just an example. This should be the version of requests that your package will not work if it is older than. Requests changed quite a bit in the 2.0 release so > 2 should work, but I have not tested it.

You should never lock a package dependencies to a specific version unless you absolutely have to. So don't do `requests == 2.23.1` or anything like that.

**Comment by leogomezz4t** [comment]
thanks
