### ISSUE TITLE
server returned a Client error. Request Failed. Status Code: 401

### ISSUE THREAD

**Issue by Hello2G** [leogomezz4t/PyTextNow_API#12]
I try to use sample

```
from TNAPI import Client

client = Client("username@gmail.com", "password")
client.send_sms("phone number", "Hello")

```
but response 

Exception has occurred: Client.FailedRequest
Could not send message. server returned a Client error. Request Failed.
Status Code: 401

**Comment by leogomezz4t** [comment]
Where did you get this sample

**Comment by leogomezz4t** [comment]
The sample you're using is a stock email address and phone number. You need to replace with you email and password for the website textnow.com. Then grab the cookie connect.sid from the application tab of chrome dev tools
