### ISSUE TITLE
Can't use `send_sms` with a body that includes the newline ('\n') character

### ISSUE THREAD

**Issue by evanye** [leogomezz4t/PyTextNow_API#21]
title says it all.
```
client.send_sms(number, "a" + "\n" + b)
```
yields

```
pytextnow.TNAPI.FailedRequest: Could not send message. server returned a Client error. Request Failed. Try resetting your authentication with client.auth_reset()
Status Code: 400
```

**Comment by bryanperez43** [comment]
`msg = f('a \\n {b}')`

**Comment by leogomezz4t** [comment]
thank you @bryanperez43.
I think to add a newline character you have to use `\\n` instead of `\n`

**Comment by evanye** [comment]
Thanks for the workaround!
Slightly concerned that there might be some vulnerability here involving unescaped characters, but not sure that folks care since it's a personal project.
