### ISSUE TITLE
Cookie expiration?

### ISSUE THREAD

**Issue by evanye** [leogomezz4t/PyTextNow_API#22]
Do the textnow cookies expire? Is there a way the client can auto-refresh them?

**Comment by leogomezz4t** [comment]
Yes they do expire. I have been working around the clock trying to figure
out how to auto-refresh them.

**Comment by evanye** [comment]
Appreciate the fast response! I'll be subscribed to this to see if you come up with something :)

**Comment by SilverStrings024** [comment]
We believe to have found it but we would appreciate any help in figuring out how to refresh it!
@evanye

**Comment by SilverStrings024** [comment]
I'm going to close this until we know we're correct about how refreshing works and get it implemented/tested.
