### ISSUE TITLE
Multiple lines

### ISSUE THREAD

**Issue by gobuster** [leogomezz4t/PyTextNow_API#32]
When I try to send something like this

client.send_sms(number, "hi\n")
or
client.send_sms(number, """hi
hi""")
I get an error
Is this supposed to happen? Or can you just not use multiple lines in a message.

**Comment by SilverStrings024** [comment]
You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead?

**Comment by gobuster** [comment]
> You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)

Yes I have still got the same error

**Comment by SilverStrings024** [comment]
> > You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)
> 
> Yes I have still got the same error

Alright, what's the traceback? Put the error in dpaste.org and post it here.

**Comment by gobuster** [comment]
> > > You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)
> > 
> > 
> > Yes I have still got the same error
> 
> Alright, what's the traceback? Put the error in dpaste.org and post it here.

https://dpaste.org/2L7i

**Comment by leogomezz4t** [comment]
We have actually had this issue before.

**Comment by SilverStrings024** [comment]
> > > > You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)
> > > 
> > > 
> > > Yes I have still got the same error
> > 
> > 
> > Alright, what's the traceback? Put the error in dpaste.org and post it here.
> 
> https://dpaste.org/2L7i
Looks like either your sid or the request was just straight out denied by text now. Try using auth_reset and giving it your sid again

**Comment by leogomezz4t** [comment]
For now you have to use `\\n` instead of `\n` but stay tuned its going to be patched in the next update

**Comment by gobuster** [comment]
> > > > > You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)
> > > > 
> > > > 
> > > > Yes I have still got the same error
> > > 
> > > 
> > > Alright, what's the traceback? Put the error in dpaste.org and post it here.
> > 
> > 
> > https://dpaste.org/2L7i
> > Looks like either your sid or the request was just straight out denied by text now. Try using auth_reset and giving it your sid again

I have tried that when I first got the error

**Comment by SilverStrings024** [comment]
> For now you have to use `\\n` instead of `\n` but stay tuned its going to be patched in the next update

That's not what he's talking about. He thinks multi-line strings won't work. 

> > > > > > You should be able to use any string as the message. Have your tried assigning the multiline string as a variable then using the variable instead? (Just as a test to make sure it's not just the function call)
> > > > > 
> > > > > 
> > > > > Yes I have still got the same error
> > > > 
> > > > 
> > > > Alright, what's the traceback? Put the error in dpaste.org and post it here.
> > > 
> > > 
> > > https://dpaste.org/2L7i
> > > Looks like either your sid or the request was just straight out denied by text now. Try using auth_reset and giving it your sid again
> 
> I have tried that when I first got the error

I didn't notice this. do what Leo said and escape the forward slash
client.send_sms(text, "test\ntest")

**Comment by leogomezz4t** [comment]
No multiline strings also won't work at the moment either.

**Comment by SilverStrings024** [comment]
> No multiline strings also won't work at the moment either.

Seriously?! Why

**Comment by leogomezz4t** [comment]
I actually didn't know they didn't work until a couple weeks ago so I'm including it in the next update. The way the request sends has to have the \n be in the string instead of an actual newline.

**Comment by SilverStrings024** [comment]
> I actually didn't know they didn't work until a couple weeks ago so I'm including it in the next update. The way the request sends has to have the \n be in the string instead of an actual newline.

hmmm weird. alright
