### ISSUE TITLE
Anyone want to upgrade the robot? If not, it will be removed.

### ISSUE THREAD

**Issue by SilverStrings024** [leogomezz4t/PyTextNow_API#39]
Hello everyone, sad news. Even though I tried to make the robot to lower the consumption of text now resources, the robot has gotten my hardware banned; likely because we tested too much but it's also possible that we messed up the configuration and made the robot easier to detect.

Now we either need to completely remove the robot, or someone else is going to need to take over the autonomous login/`connect.sid` harvesting. Without the robot or some other way to autonomously get the `connect.sid` cookie value, everyone will need to do it themselves (login, go into dev tools, etc). Mind you, your sid will likely change every time you log out or, sometimes, it changes on refresh or randomly so it's much more likely that your program will fail to send texts.

Sadly, the convenience of the robot getting the SID for us, logging back in if we were logged out, refreshing the page at random intervals, etc. is now an impossibility. If someone would like to write something to make it work, obfuscate it then put it in the package, please do!
Otherwise, I'm sorry to announce that fully autonomous login/sid harvesting is no longer viable. :disappointed:

**Comment by ratlaco** [comment]
Hello, have been using this for some time. How can I help? How can I upgrade the robot? I try to get the developer docs from textnow, but I couldn't find it.

**Comment by aaronjamt** [comment]
> Hello, have been using this for some time. How can I help? How can I upgrade the robot? I try to get the developer docs from textnow, but I couldn't find it.

There *are* no dev docs. It's closed source and this project is something that TN would be... less than pleased to find out about. The docs are whatever we reverse engineer.

**Comment by SilverStrings024** [comment]
> 
> 
> Hello, have been using this for some time. How can I help? How can I upgrade the robot? I try to get the developer docs from textnow, but I couldn't find it.

Hi! I'm the one that made the robot and, sadly, it looks liek text now is NOT happy about it.
There are a few ways you can help. If you'd like to join the discord and/or message me directly, we can try to figure out what we can do in this case. I've tried a few things since posting this and I seem to have been hardware (fingerprint) banned so we will have to be fairly careful. I have a few methods to prevent this but I refuse to make it public because I'm developing something at the moment that uses this method.

https://discord.gg/2cr9QenAy4

**Comment by haxembourg** [comment]
im looking for a free SMS/MMS messaging service that I can use in Python but everything seems to be paid and this looks like the best option so is there any way i can help with it?

**Comment by SilverStrings024** [comment]
> im looking for a free SMS/MMS messaging service that I can use in Python but everything seems to be paid and this looks like the best option so is there any way i can help with it?

You'll want to join the discord. I'm about to let everyone know the only two ways this will happen.

**Comment by haxembourg** [comment]
oh ok, what's the link? the other one dosent work

**Comment by SilverStrings024** [comment]
> oh ok, what's the link? the other one dosent work

https://discord.gg/84ppHfHeKt

**Comment by aaronjamt** [comment]
@haxembourg Yeah, this project's kinda been abandoned. I've kinda been doing the majority of the work but I'm losing interest in it.

**Comment by pyroTM** [comment]
> https://discord.gg/84ppHfHeKt

link doesn't work send again please

**Comment by SilverStrings024** [comment]
https://discord.gg/NYUx4xRzq2
