### ISSUE TITLE
Could not send message. server return a Server error. Request Failed. Status Code: 520

### ISSUE THREAD

**Issue by fateh-sarfaraz** [leogomezz4t/PyTextNow_API#40]
I don't understand why i am getting this error Few days back i could run textapp automatically using pytextnow_api but suddenly it's not working and i am unable to figure out the problem

**Comment by SilverStrings024** [comment]
Have you changed your code at all or has your sid changed?

**Comment by ovr-hit** [comment]
Same thing happening to me all of a sudden.

> I don't understand why i am getting this error Few days back i could run textapp automatically using pytextnow_api but suddenly it's not working and i am unable to figure out the problem

**Comment by SilverStrings024** [comment]
> Same thing happening to me all of a sudden.
> 
> > I don't understand why i am getting this error Few days back i could run textapp automatically using pytextnow_api but suddenly it's not working and i am unable to figure out the problem


To be honest; text now may just be cracking down or changing the way they handle request authentications. Add something to your code to print out the connect.sid cookie for each request. If it isn't found or changes for each request then this package is most likely going to become blocked/obsolete

**Comment by leogomezz4t** [comment]
Alright I'll look into it and try and push a bug fix soon. It may takes some time because of the impending 2.0.0 update. I'm just going to make a smaller 1.1.8 patch soon.

**Comment by ovr-hit** [comment]
Do you have a timeframe it will be out by? I'm really depending on it. Thanks for all the work you do on this, im infinitely grateful for people like you.

**Comment by SilverStrings024** [comment]
> Alright I'll look into it and try and push a bug fix soon. It may takes some time because of the impending 2.0.0 update. I'm just going to make a smaller 1.1.8 patch soon.

@leogomezz4t What's the issue?

**Comment by ovr-hit** [comment]
Any word? @leogomezz4t @SilverStrings024

**Comment by SilverStrings024** [comment]
> Any word? @leogomezz4t @SilverStrings024

I asked him about it on the discord (now deleted because no one was working on anything nor talking about trying anything other than Aaron Jamt and I) and he said it seemed as though they were updating the authentication methods so it's **POSSIBLE** the sid is not longer a valid method.

So, since I would assume you're using the main/stable branch something I could suggest is to clone the repo then update it to do a simple check on each request to make sure the connect.sid cookie value is the same and if it's not, update it. If that doesn't work then I was correct and they indeed updated their authentication methods to make the connect.sid cookie obsolete. Which means this package is no longer viable unless someone makes a new robot and obfuscates the code (REALLY well). Which, if someone did, would mean this package becomes nothing but a texting robot instead of an API package.

If I can find some free time, I'll see what I can do but since I was banned it's likely not gonna happen on my side. If you'd like to brainstorm on how we can bypass this with @aaronjamt and I, then I can make a new discord and we can discuss it.

**Comment by ovr-hit** [comment]
@SilverStrings024 I'm down to help out but I'm not the most experienced, I can definitely help tho. (After all I'm only 14 tryna piece together some code) Send the Discord link, let's see what we can do.

**Comment by SilverStrings024** [comment]
> @SilverStrings024 I'm down to help out but I'm not the most experienced, I can definitely help tho. (After all I'm only 14 tryna piece together some code) Send the Discord link, let's see what we can do.

Alright, here you go. Talk with you there.
https://discord.gg/sv3kBkQm

**Comment by NJC0-a** [comment]
I'd also like a discord link. The ones you've sent are invalid. I'm depending on this API for one of my projects and I've yet to find any alternatives that are similar to text-now.

**Comment by NJC0-a** [comment]
@SilverStrings024 I'd also like a discord link. The ones you've sent are invalid. I'm depending on this API for one of my projects and I've yet to find any alternatives that are similar to text-now.

**Comment by leogomezz4t** [comment]
So I did some testing and it looks like textnow.com now requires a _csrf cookie to send a message and perhaps other methods

**Comment by SilverStrings024** [comment]
https://discord.gg/sEBe6ERt

**Comment by SilverStrings024** [comment]
> @SilverStrings024 I'd also like a discord link. The ones you've sent are invalid. I'm depending on this API for one of my projects and I've yet to find any alternatives that are similar to text-now.

https://discord.gg/sEBe6ERt

**Comment by ovr-hit** [comment]
@leogomezz4t Have you figured it all out?

**Comment by leogomezz4t** [comment]
I think so but I'm still formatting all the new methods with the new cookie so there should be a patch soon. Keep in mind you will have to include the _csrf cookie in the Client constructor much like the sid cookie

**Comment by ovr-hit** [comment]
Great! Notify us when it's ready, thanks!

**Comment by ovr-hit** [comment]
> > @SilverStrings024 I'm down to help out but I'm not the most experienced, I can definitely help tho. (After all I'm only 14 tryna piece together some code) Send the Discord link, let's see what we can do.
> 
> Alright, here you go. Talk with you there.
> https://discord.gg/sv3kBkQm

Hehe uh unban please im very sorry

**Comment by SilverStrings024** [comment]
> > > @SilverStrings024 I'm down to help out but I'm not the most experienced, I can definitely help tho. (After all I'm only 14 tryna piece together some code) Send the Discord link, let's see what we can do.
> > 
> > 
> > Alright, here you go. Talk with you there.
> > https://discord.gg/sv3kBkQm
> 
> Hehe uh unban please im very sorry

I didn't ban you, if Aaron did I'll unban you.

**Comment by ovr-hit** [comment]
Send another invite, this one's invalid.

**Comment by SilverStrings024** [comment]
https://discord.gg/NYUx4xRzq2

**Comment by SilverStrings024** [comment]
Join the discord at the link above.

**Comment by ovr-hit** [comment]
@SilverStrings024 no, I'm banned, just tried to join again and it didn't work.

**Comment by SilverStrings024** [comment]
> @SilverStrings024 no, I'm banned, just tried to join again and it didn't work.

Then I need your username. Aaron said you only left so, let me get that I'll friend request you then unban you. Honestly not sure why he would do that though.

**Comment by ovr-hit** [comment]
`Viviotic#3929
`
thanks

**Comment by SilverStrings024** [comment]
> `Viviotic#3929
> `
> thanks

It said you don't accept friend requests.

**Comment by ovr-hit** [comment]
> > `Viviotic#3929
> > `
> > thanks
> 
> It said you don't accept friend requests.
> 

Try now please.

**Comment by leogomezz4t** [comment]
Alr looks like the request also requires a csrf_token header to work

**Comment by leogomezz4t** [comment]
I don't know how to find the header without first sending a message in textnow.com. If anyone has an idea or wants to help then post on this thread

**Comment by wunter8** [comment]
I think I got it working and will submit a PR later today. I've only tested it for sending a couple SMS. Some of the changes might need to be propagated to the other methods.

**Comment by ovr-hit** [comment]
> I think I got it working and will submit a PR later today. I've only tested it for sending a couple SMS. Some of the changes might need to be propagated to the other methods.

That's great to hear, stay in touch on this thread please!! Much appreciated.

**Comment by leogomezz4t** [comment]
Great thanks!

**Comment by NJC0-a** [comment]
@ovr-hit The pull request wunter did is working. I'm just telling you cause I know you also were depending on this project just as I was so yeah.

**Comment by leogomezz4t** [comment]
@wunter8 PR worked great so I debugged and renamed some variables and made a new PR. I'll merge it soon

**Comment by ovr-hit** [comment]
> @wunter8 PR worked great so I debugged and renamed some variables and made a new PR. I'll merge it soon

I'll just wait for the merge, thanks!

Message here when its ready.

**Comment by leogomezz4t** [comment]
Will do!

**Comment by wunter8** [comment]
@ovr-hit It looks like my changes have been merged!

**Comment by ovr-hit** [comment]
> @ovr-hit It looks like my changes have been merged! But the changes haven't been pushed to pypi/pip, so you'll have to install the latest files from Github

Is there an updated README doc? for grabbing the CSRF token and implementing it?

**Comment by ovr-hit** [comment]
> The README hasn't been updated yet. In addition to the `connect.sid` cookie you grab from the browser using the Developer Tools (same as before), you'll need to grab the `_csrf` cookie using the same method

Ok perfect, thanks.

**Comment by ovr-hit** [comment]
> The README hasn't been updated yet. In addition to the `connect.sid` cookie you grab from the browser using the Developer Tools (same as before), you'll need to grab the `_csrf` cookie using the same method

Ok perfect, thanks.

**Comment by leogomezz4t** [comment]
Yeah I merged the changes yesterday and today I'll update the README and publish 1.1.8 on pypi

**Comment by ovr-hit** [comment]
> Yeah I merged the changes yesterday and today I'll update the README and publish 1.1.8 on pypi

Perfect!!

**Comment by leogomezz4t** [comment]
1.1.8 has been pushed to the `main` branch as well as published on PyPi
https://pypi.org/project/PyTextNow/1.1.8/

**Comment by leogomezz4t** [comment]
There are still documentation and stuff to be added but functionality is working
