### ISSUE TITLE
can't clone

### ISSUE THREAD

**Issue by ouam3r** [leogomezz4t/PyTextNow_API#46]
Hello,

Everytime I try to > git clone https://github.com/WuGomezCode/TextNow-API.git

I end up with this : 

#remote: Repository not found.
#fatal: repository 'https://github.com/WuGomezCode/TextNow-API.git/' not found

Can you please help?
Thanks in advance

**Comment by leogomezz4t** [comment]
Could you copy the whole trace log and post it here

**Comment by ouam3r** [comment]
mk007@D34D3ND:~$ sudo git clone https://github.com/leogomezz4t/PyTextNow_API
Cloning into 'PyTextNow_API'...
remote: Enumerating objects: 948, done.
remote: Counting objects: 100% (405/405), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 948 (delta 260), reused 291 (delta 162), pack-reused 543
Receiving objects: 100% (948/948), 16.11 MiB | 861.00 KiB/s, done.
Resolving deltas: 100% (574/574), done.
mk007@D34D3ND:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  PyTextNow_API  Templates  Videos  YANDEX-BROWSER-KEY.GPG
mk007@D34D3ND:~$ cd PyTextNow_API/
mk007@D34D3ND:~/PyTextNow_API$ l
examples/  get_cookie.mp4  get_username.mp4  LICENSE  MANIFEST.in  pytextnow/  README.md  requirements.txt  setup.py
mk007@D34D3ND:~/PyTextNow_API$ ls
examples  get_cookie.mp4  get_username.mp4  LICENSE  MANIFEST.in  pytextnow  README.md  requirements.txt  setup.py
mk007@D34D3ND:~/PyTextNow_API$ cd pytextnow/
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ ls
error.py  __init__.py  login.py  message_container.py  message.py  multi_media_message.py  TNAPI.py  user_cookies.json
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ cat user_cookies.json 
{"leojwu18": {"sid": "s%3AeAXhdKRMXEKUFDmd1xYLoIqxR2dHSAIL.tlVkIiG1%2BXtF%2Bt9Lgw%2Fcr78KDliOLzCYfgC6BM7eAo0", "csrf": "s%3AsHuuA5YYh8_5BNSAjYR7PPTt.I8lIB2yFZOB35GMI7NuI57tEzN604FYoG3qNcGZ2d%2Fk"}}mk007@D34D3ND:~/PyTextNow_API/pytextnow$ client.auth_reset()
> 
> 
> ^C
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ cat user_cookies.json 
{"leojwu18": {"sid": "s%3AeAXhdKRMXEKUFDmd1xYLoIqxR2dHSAIL.tlVkIiG1%2BXtF%2Bt9Lgw%2Fcr78KDliOLzCYfgC6BM7eAo0", "csrf": "s%3AsHuuA5YYh8_5BNSAjYR7PPTt.I8lIB2yFZOB35GMI7NuI57tEzN604FYoG3qNcGZ2d%2Fk"}}mk007@D34D3ND:~/PyTextNow_API/pytextnow$ 
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ 
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ 
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ sudo nano user_cookies.json 
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ client.send_sms("12127290149", "Hello World!")
bash: syntax error near unexpected token `"12127290149",'
mk007@D34D3ND:~/PyTextNow_API/pytextnow$ client.send_sms("+12127290149", "Hello World!")
bash: syntax error near unexpected token `"+12127290149",'

**Comment by ouam3r** [comment]
Thank you very much Sir, I appreciate your support. Just for clarification in this line : ("username", cookies and whatnot). username name is my textnow username, right? What should go in cookies and whatnot? What's syntax of it?
