### ISSUE TITLE
Issue Sending Messages

### ISSUE THREAD

**Issue by kwang38** [leogomezz4t/PyTextNow_API#47]
I am having issues trying to send someone a message with the new line character (\n).

For example, if the content of the message is "Hello World", the message gets sent. However, if the content of the message we want to send is "Hello\nWorld", then I get the following error message:

pytextnow.error.FailedRequest: Could not send message. server returned a Client error. Request Failed. Try resetting your authentication with client.auth_reset() 
Status Code: 400

**Comment by leogomezz4t** [comment]
@kwang38  Thanks to @wunter8 this bug has been fixed in the new 1.2.0 update
