### ISSUE TITLE
issue sending sms

### ISSUE THREAD

**Issue by Bangbang901** [leogomezz4t/PyTextNow_API#50]
I have an issue sending sms. In wich path do i need to be to execute the send sms command and also what is the full command to send an sms. thank you

**Comment by leogomezz4t** [comment]
Well it is a python library so you have to import it to your python script.
```python
import pytextnow

client = pytextnow.Client("username", "password", sid="sid", csrf="csrf")

client.send_sms("number", "message")
```

**Comment by Bangbang901** [comment]
Please tell me all the steps to send a message. I know how to change my id and cookies in the txt file manually but the other commands does not work for me. I have installed requirements.txt. I also have python installed. Tell me what i am missing. Below is the respond i get when i try to run the commands.



client = pytextnow.Client("username", "password", sid="sid", csrf="csrf")
'client' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kk-deng** [comment]
> Please tell me all the steps to send a message. I know how to change my id and cookies in the txt file manually but the other commands does not work for me. I have installed requirements.txt. I also have python installed. Tell me what i am missing. Below is the respond i get when i try to run the commands.
> 
> client = pytextnow.Client("username", "password", sid="sid", csrf="csrf") 'client' is not recognized as an internal or external command, operable program or batch file.

Looks like you run this line on cmd. You should create your own .py file and run this code snippet.

**Comment by leogomezz4t** [comment]
> Please tell me all the steps to send a message. I know how to change my id and cookies in the txt file manually but the other commands does not work for me. I have installed requirements.txt. I also have python installed. Tell me what i am missing. Below is the respond i get when i try to run the commands.
> 
> 
> 
> 
> 
> 
> 
> client = pytextnow.Client("username", "password", sid="sid", csrf="csrf")
> 
> 'client' is not recognized as an internal or external command,
> 
> operable program or batch file.

Yes this is not a command line interface (CLI). It is a python library so you will have to make a python file (.py) then write your code there and try running it with python

**Comment by Bangbang901** [comment]
Can i pay you to make me a CLI?

**Comment by leogomezz4t** [comment]
> Yes of course. Do you have a discord or something to communicate?

**Comment by Bangbang901** [comment]
Telegram? @Onlym0neyz

**Comment by leogomezz4t** [comment]
Sure
