### ISSUE TITLE
Anyone can help? - message not sent

### ISSUE THREAD

**Issue by jkessous** [leogomezz4t/PyTextNow_API#53]
Hi All,
First of all i would like to thank the developer for this script.
i am trying to make it work but i get the following error when trying to send.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytextnow\TNAPI.py", line 272, in send_sms
    self.request_handler(response.status_code)
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytextnow\TNAPI.py", line 315, in request_handler
    raise FailedRequest(status_code)
pytextnow.error.FailedRequest: Could not send message. server return a Server error. Request Failed.
Status Code: 520

thanks

**Comment by leogomezz4t** [comment]
What version of pytextnow are you using?

**Comment by jkessous** [comment]
I went according to the instructions:
C:\Users\Jonathan>pip install PyTextNow
Requirement already satisfied: PyTextNow in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.1.9)
Requirement already satisfied: requests~=2.25.1 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from PyTextNow) (2.25.1)
Requirement already satisfied: setuptools~=57.0.0 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from PyTextNow) (57.0.0)
Requirement already satisfied: python-dateutil~=2.8.1 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from PyTextNow) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil~=2.8.1->PyTextNow) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests~=2.25.1->PyTextNow) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests~=2.25.1->PyTextNow) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests~=2.25.1->PyTextNow) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jonathan\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests~=2.25.1->PyTextNow) (1.26.8)

**Comment by jkessous** [comment]
Any idea what am i doing wrong?
thanks

**Comment by leogomezz4t** [comment]
Yeah there is a new version of pytextnow. Version 1.2.0 you can install it
with pip install pytextnow —upgrade

**Comment by jkessous** [comment]
I did upgrade but still getting the same error.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytextnow\TNAPI.py", line 272, in send_sms
    self.request_handler(response.status_code)
  File "C:\Users\Jonathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytextnow\TNAPI.py", line 315, in request_handler
    raise FailedRequest(status_code)
pytextnow.error.FailedRequest: Could not send message. server return a Server error. Request Failed.
Status Code: 520

**Comment by jkessous** [comment]
I found the issue - it was on my side.
I didnt import the csrf cookie - i went according to the video and it didnt mention anything there :)
thanks it is working great,
