### ISSUE TITLE
Can you make this to send to multiple numbers?

### ISSUE THREAD

**Issue by ernestkharichkin1997** [leogomezz4t/PyTextNow_API#54]
I want to use it for marketing, If you can please make a video how to use it (where I put the numbers, message, username, cookie, sid and what is the command to run it. (I'm new on this python, but your project sound very interesting) I will wait your answer.  You can contact me directly at: ernestkharichkin1997@gmail.com  Thank you so much

**Comment by leogomezz4t** [comment]
You can send to multiple messages. Just create a for loop that goes through each number and send to them.
