### ISSUE TITLE
Links Not Being Able to send.

### ISSUE THREAD

**Issue by Unbandit2006** [leogomezz4t/PyTextNow_API#55]
Hello there,
I want to send links by SMS and for some reason on TextNow it appears, but on my phone, it doesn't appear.

This is my code that doesn't work:
``` python
for number in phone_numbers:
    for result in range(result_count):
        link = f'https://www.themoviedb.org/movie/{content["results"][result]["id"]}'
        client.send_sms(number, link)
```
I am working on python version 3.9.9 && PyTextNow version 1.1.9 && Windows 10

**Comment by leogomezz4t** [comment]
I've had this issue for awhile and have been unable to fix it. It seems like Textnows API doesn't allow direct links. I do know that adding a period at the end or beginning of the link can sometimes fix the problem
